### ISSUE TITLE
Output of thexb --iqtree_external lacks a header for --topobinner

### ISSUE THREAD

**Issue by docmanny** [harris-2374/THEx#1]
Hey! There's a very simple issue (and fix) for `thexb` when one is importing trees from an external iqtree run. 

ISSUE:
-------

When running `thexb --iqtree_external -i ./input -o ./output`, the resulting `TreeViewer_input_file.xlsx` only has 3 headers: Chromosome, Window, and NewickTree. The next step in the pipeline (`thexb --topobinner`) is expecting an input file with 4 headers, however: Chromosome, Window, NewickTree, and TopologyID. 

Simply adding the missing column to the header in the XLSX file using Excel makes it work perfectly downstream. It seems like this issue can be fixed by either modifying `create_TreeViewer_input` in [STAGE_iqtree_external.py](https://github.com/harris-2374/THEx/blob/main/src/thexb/STAGE_iqtree_external.py) to create the missing column; or change `tv_header_validation` in [STAGE_topobinner.py](https://github.com/harris-2374/THEx/blob/main/src/thexb/STAGE_topobinner.py) to only expect the first 3 columns. 

Note that the same issue in theory also exists for `--iqtree` as far as I can see, since the function `create_TreeViewer_input` there is also only generating 3 columns...

**Comment by harris-2374** [comment]
Hi! I have this fixed in v1.0.3, which should be released soon. I will keep this open until the next update is pushed. Thanks for bringing this to my attention!
