### ISSUE TITLE
Unaligned sequences error in trimal

### ISSUE THREAD

**Issue by lauterbur** [harris-2374/THEx#3]
Hi,

I'm running through the thexb pipeline step by step and get an error from multiprocessing that seems to result from an issue in the fasta window file passed to trimal.

The windowing step runs without error: ```thexb --minifastas -c config_myotis.ini```
```----------Input Parameters----------
Command: thexb --minifastas -c config_myotis.ini
Input directory: /labstorage/lauterbur/THEx/scaffoldMyotisAlignments
Output directory: /labstorage/lauterbur/THEx/THExMyotisOutput/windowed_fastas
Window size: 10kb
------------------------------------
Parsing 23 files into 10kb windows
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:08<00:00,  2.57it/s]
```

On running the trimal step ```thexb --trimal -c config_myotis.ini``` 
I get the following error output:
```----------Input Parameters----------
Command: thexb --trimal -c config_myotis.ini
Input directory: /labstorage/lauterbur/THEx/THExMyotisOutput/windowed_fastas
Gap threshold: 0.5
Minimum post-trimal sequence length: 1000
Drop windows with missing samples: True
------------------------------------
  0%|                                                                                                                                       | 0/23 [00:00<?, ?it/s]
multiprocess.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/thexb/STAGE_trimal.py", line 139, in run_trimal_per_chrom
    subprocess.run([f'trimal -fasta -in {quote(f.as_posix())} -out {quote(file_output_name.as_posix())} -gapthreshold {TRIMAL_THRESH}'], shell=True, check=True, stderr=subprocess.DEVNULL)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['trimal -fasta -in /labstorage/lauterbur/THEx/THExMyotisOutput/windowed_fastas/flipped_Myotis_nodupes_mMyotis_NW_023416316.reformat.Concat2Files/flipped-Myotis-nodupes-mMyotis-NW-023416316.reformat.Concat2Files_970001_980000.fasta -out /labstorage/lauterbur/THEx/THExMyotisOutput/trimal_filtered_windows/flipped_Myotis_nodupes_mMyotis_NW_023416316.reformat.Concat2Files/flipped-Myotis-nodupes-mMyotis-NW-023416316.reformat.Concat2Files_970001_980000.fasta -gapthreshold 0.5']' returned non-zero exit status 255.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lauterbur/anaconda3/envs/thex/bin/thexb", line 10, in <module>
    sys.exit(main())
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/thexb/__main__.py", line 815, in main
    trimal(windowed_fasta_dir, filtered_outdir, WORKING_DIR, TRIMAL_THRESH, TRIMAL_MIN_LENGTH, TRIMAL_DROP_WINDOWS, MULTIPROCESS, LOG_LEVEL)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/thexb/STAGE_trimal.py", line 210, in trimal
    p_umap(
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/p_tqdm/p_tqdm.py", line 84, in p_umap
    result = list(generator)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/p_tqdm/p_tqdm.py", line 54, in _parallel
    for item in tqdm_func(map_func(function, *iterables), total=length, **kwargs):
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/multiprocess/pool.py", line 870, in next
    raise value
subprocess.CalledProcessError: Command '['trimal -fasta -in /labstorage/lauterbur/THEx/THExMyotisOutput/windowed_fastas/flipped_Myotis_nodupes_mMyotis_NW_023416316.reformat.Concat2Files/flipped-Myotis-nodupes-mMyotis-NW-023416316.reformat.Concat2Files_970001_980000.fasta -out /labstorage/lauterbur/THEx/THExMyotisOutput/trimal_filtered_windows/flipped_Myotis_nodupes_mMyotis_NW_023416316.reformat.Concat2Files/flipped-Myotis-nodupes-mMyotis-NW-023416316.reformat.Concat2Files_970001_980000.fasta -gapthreshold 0.5']' returned non-zero exit status 255.
Traceback (most recent call last):
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/multiprocess/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/multiprocess/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/multiprocess/pool.py", line 692, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/multiprocess/pool.py", line 674, in _help_stuff_finish
    inqueue._reader.recv()
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/multiprocess/connection.py", line 259, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/dill/_dill.py", line 286, in loads
    return load(file, ignore, **kwds)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/dill/_dill.py", line 272, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/site-packages/dill/_dill.py", line 419, in load
    obj = StockUnpickler.load(self)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/multiprocessing/managers.py", line 933, in RebuildProxy
    return func(token, serializer, incref=incref, **kwds)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/multiprocessing/managers.py", line 783, in __init__
    self._incref()
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/multiprocessing/managers.py", line 837, in _incref
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/home/lauterbur/anaconda3/envs/thex/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

The issue seems to be in trimal, from the subprocess.CalledProcessError, so I run the trimal command that generated that error ```trimal -fasta -in /labstorage/lauterbur/THEx/THExMyotisOutput/windowed_fastas/flipped_Myotis_nodupes_mMyotis_NW_023416316.reformat.Concat2Files/flipped-Myotis-nodupes-mMyotis-NW-023416316.reformat.Concat2Files_970001_980000.fasta -out /labstorage/lauterbur/THEx/THExMyotisOutput/trimal_filtered_windows/flipped_Myotis_nodupes_mMyotis_NW_023416316.reformat.Concat2Files/flipped-Myotis-nodupes-mMyotis-NW-023416316.reformat.Concat2Files_970001_980000.fasta -gapthreshold 0.5```

and get ```ERROR: The sequences in the input alignment should be aligned in order to use trimming method.```

The other window files generated by the minifasta step seem to work fine, and the one with the issue is the end of the chromosome and only a little over half the size of the others. In fact this seems to be happening for one window file per chromosome, always the last one (or a few at the end). This means that I can get away with just deleting each of those problematic window files, but that's not ideal, especially if this is caused by some parameter choice I've naively made. I've attached the config file and the window fasta here. Do you know what might be going wrong? Thanks!
[window.fasta.txt](https://github.com/harris-2374/THEx/files/11537502/window.fasta.txt)
[config.ini.txt](https://github.com/harris-2374/THEx/files/11537504/config.ini.txt)

**Comment by harris-2374** [comment]
Hi @lauterbur,

Thank you for bringing this up! Based on your error, the problem may lie in your multiple-sequence alignment (MSA). Currently, THEx is designed to work with reference-based alignments where all samples are mapped to a single coordinate system (the reference), making all alignments the same length. We are working on updates for reference-free and pangenome approaches for THEx, but until then, THEx requires your MSA to be the same length for all samples. With this, you can either remove the troublesome windows (I agree this is not ideal), or you can align your reads/assemblies to your best genome assembly with something like bwa (short-reads) or minimap2 (long-reads/assemblies). Those are only two examples, but there are other programs that can accomplish the same thing. I can provide further information on the pipeline we typically use for MSA generation if you are interested. 

I hope this helps!

Best,
Andrew

**Comment by lauterbur** [comment]
Hi Andrew,

That does appear to have been the problem. I was converting from a maf file and had accidentally left in some blocks that didn't have all of the species, which messed things up downstream. Thanks for helping me to figure that out!

I'm now running into a new issue with the pairwise filter step. There are no errors reported, but the result files end up with stray header lines, like so:
\>species1
AAGAGGGTCTCATGCCTAGATGATAACGTTTTCATTTAGTTCAGTGCCTCCCATTAATTTTGACTGTACTTCTCAGAAGA
... more normal lines ...
TCAGTTTATGTTGTTCATTATATTCCACAAATGAGTGAGATCATGTGATATTTACCTTTCTCCAAATGGC>speci
es2CTTTCCTTTAAGGATGCCAAGAATCCATTCCCTTCAATCCAGACATTGTTCAGGCGAAGAAGGCCTCA
\>species2
GTTTTCATTTAGTTCAGTGCCTCCCATTAATTTTGACTGTTCTTCTCAGAAGAATTGTGCTGGCAAAATATAAGAGAGAT


Each species is getting the header of the next species in the alignment tacked on to the end of its sequence. The sequence of the next species then starts a few bases after the end of the bit that got tacked on to the previous species, so species2's actual sequence is:
\>species2
CTTTCCTTTAAGGATGCCAAGAATCCATTCCCTTCAATCCAGACATTGTTCAGGCGAAGA
AGGCCTCA _TGCCTAGATGATAAT_ GTTTTCATTTAGTTCAGTGCCTCCCATTAATTTTGAC
TGTTCTTCTCAGAAGAATTGTGCTGGCAAAATATAAGAGAGATTCTCAAAAAATGGATCC

(I've put the missing bases between the end of the tacked on bit and the beginning of the start after the header in italic just so they're easy to see here, there are no spaces or anything else different about them in the actual file.)

To be clear, the input fasta files are now all the same length, and the trimal step isn't having any issues and creates fasta files that are fine. The pairwise filtration step doesn't report any problems during its run, but each of the resulting fasta files looks like this, repeated for each alignment in the file. (So the only alignment that doesn't have it is the last, since there is no next species.)

Any thoughts?

**Comment by harris-2374** [comment]
Hi @lauterbur,

Have you tried rerunning the pairwise filtration step to see if it is repeatable? Also, can you provide a window from the Trimal output and one from the pairwise filter step that is showing this issue? That could help me better understand what is happening. You can email it to me if that is easier (ajharris _at_ cvm.tamu.edu).

Thanks,
Andrew

**Comment by lauterbur** [comment]
Hi Andrew,

Yup, and I've tried running deleting everything and running the pipeline from scratch and it still does this. I'll email the files to you shortly.

Thanks!
Elise

**Comment by lorenalorenzo** [comment]
Hi again,
Is there any solution to this issue @harris-2374 ??? Or did you find any alternative @lauterbur ??? 

Thanks in advance.
Best,
Lorena

**Comment by harris-2374** [comment]
Hi @lorenalorenzo,

Apologies for the delay, I have been working with @lauterbur on resolving this, and we did end up finding a solution! I will have a fix in the next update that should be pushed here in the next week or two. 

Best,
Andrew

**Comment by lorenalorenzo** [comment]
Hi @harris-2374 , any news about that?

Best,
Lorena

**Comment by harris-2374** [comment]
Hi @lorenalorenzo,

My deepest apologies for the delay. My wife and I just welcomed our first child into the world, so my hands have been a little tied up recently. I just pushed v1.0.3 for Linux and MacOS, and Windows will follow tomorrow. If you run into any further issues, please feel free to reopen this issue. 

Best,
Andrew

**Comment by lorenalorenzo** [comment]
Hi Andrew,
My warmest congrats for your new child, I wish all of you the best. 
Many sorry for the inconveniences I may have cause and many thanks for the good news! 

My best,
Lorena
