### ISSUE TITLE
Unable to Install THEx Package on My Cluster

### ISSUE THREAD

**Issue by mataman2017** [harris-2374/THEx#4]
I'm currently trying to install the THEx package on my cluster by following the provided instructions. However, I seem to be encountering an issue during installation. My terminal gets stuck during the installation process. Here are the commands I've used:

(thex_env) [jg2334@della8 B_225_nomaf_mask-miss_auto_neutral]$ conda install thex -c ajharris_2374

Here's the output I receive:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -\ 

Is there any specific reason why I'm encountering this issue during installation?
Do I need to install any additional dependencies before attempting to install the THEx package via Conda?
Any help or insights would be greatly appreciated. Thank you!

**Comment by harris-2374** [comment]
Hi @mataman2017!

I am sorry to hear you are having trouble installing THEx. Someone brought up a similar issue before (#2) and resolved their issue by creating a .yml environment file with the required dependencies. I can create one for you and upload it to the repository. This way, anyone else who runs into this issue can also try out the .yml approach. I just got back from traveling, and I'm currently catching up on a few things, so if you can give me a day or two, I will have it uploaded for you!

**Comment by harris-2374** [comment]
Hi @mataman2017,

I've added conda environment files with the dependencies for THEx. You can install the dependencies first using "conda env create -f linux_osx_deps.yaml", then you can run "conda install -c ajharris_2374 thex" to install THEx. If you still run into problems, feel free to reopen this issue.

Best,
Andrew
